"""
Feature Engineering Module
Creates rolling window statistics, derived features, and risk scores.
"""
import pandas as pd
import numpy as np

def add_rolling_features(df, windows=None):
    """
    Add rolling means, standard deviations, and exponential moving averages.
    Also create gaze deviation, head velocity, and event densities.
    
    Parameters:
        df (pd.DataFrame): cleaned merged data with timestamp index or sorted by time.
        windows (list): list of window sizes in seconds. Default [5, 10, 15, 30].
    """
    if windows is None:
        windows = [5, 10, 15, 30]
    
    df_feat = df.copy()
    
    # Gaze deviation (absolute angle from center)
    if 'eye_gaze_angle' in df_feat.columns:
        df_feat['gaze_deviation'] = df_feat['eye_gaze_angle'].abs()
    
    # Head velocity (first difference)
    if 'head_pose_x' in df_feat.columns and 'head_pose_y' in df_feat.columns:
        df_feat['head_velocity_x'] = df_feat['head_pose_x'].diff().fillna(0)
        df_feat['head_velocity_y'] = df_feat['head_pose_y'].diff().fillna(0)
        df_feat['head_acceleration_x'] = df_feat['head_velocity_x'].diff().fillna(0)
        df_feat['head_acceleration_y'] = df_feat['head_velocity_y'].diff().fillna(0)
    
    # Rolling features for gaze and audio
    for w in windows:
        if 'eye_gaze_angle' in df_feat.columns:
            df_feat[f'gaze_rolling_mean_{w}s'] = df_feat['eye_gaze_angle'].rolling(window=w, min_periods=1).mean()
            df_feat[f'gaze_rolling_std_{w}s'] = df_feat['eye_gaze_angle'].rolling(window=w, min_periods=1).std().fillna(0)
        if 'audio_db' in df_feat.columns:
            df_feat[f'audio_rolling_mean_{w}s'] = df_feat['audio_db'].rolling(window=w, min_periods=1).mean()
            df_feat[f'audio_rolling_std_{w}s'] = df_feat['audio_db'].rolling(window=w, min_periods=1).std().fillna(0)
    
    # Exponential moving averages
    for span in [5, 10, 20]:
        if 'eye_gaze_angle' in df_feat.columns:
            df_feat[f'gaze_ema_{span}'] = df_feat['eye_gaze_angle'].ewm(span=span, adjust=False).mean()
        if 'audio_db' in df_feat.columns:
            df_feat[f'audio_ema_{span}'] = df_feat['audio_db'].ewm(span=span, adjust=False).mean()
    
    # Event density (sum of events in last 10 seconds)
    if 'tab_switches' in df_feat.columns:
        df_feat['tab_switch_density'] = df_feat['tab_switches'].rolling(window=10, min_periods=1).sum()
    if 'copy_paste' in df_feat.columns:
        df_feat['copy_paste_density'] = df_feat['copy_paste'].rolling(window=10, min_periods=1).sum()
    
    # Simple cumulative risk score (rule-based, will be supplemented by Rules Engine)
    # This is a lightweight indicator; the dedicated RiskEngine will compute more elaborate scores.
    if all(col in df_feat.columns for col in ['gaze_deviation', 'audio_db', 'tab_switches', 'copy_paste']):
        df_feat['cumulative_risk_score'] = (
            (df_feat['gaze_deviation'] > 15).astype(int) * 5 +
            (df_feat['audio_db'] > 60).astype(int) * 3 +
            (df_feat['tab_switches'] > 0).astype(int) * 10 +
            (df_feat['copy_paste'] > 0).astype(int) * 15
        ).rolling(window=10, min_periods=1).sum()
    
    return df_feat

def drop_initial_na(df):
    """
    Remove rows where any rolling feature (starting with 'rolling' or 'ema' or 'density' or 'cumulative') is NaN.
    This occurs at the beginning of the series.
    """
    # Identify columns that are generated by rolling operations
    rolling_cols = [col for col in df.columns if any(key in col for key in ['rolling', 'ema', 'density', 'cumulative'])]
    if rolling_cols:
        df_clean = df.dropna(subset=rolling_cols, how='any')
    else:
        df_clean = df
    return df_clean

def create_all_features(merged_df):
    """
    Wrapper that applies all feature engineering steps and returns the final feature-rich DataFrame.
    """
    df = add_rolling_features(merged_df)
    df = drop_initial_na(df)
    return df